### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/sharer.js#102]
Sharer.js needs a new website!  With all the current implemented API documented and some examples. Since i am terrible at frontend, i am taking suggestions on some cool designs that can help improve user experience.

All work must be pushed to the `gh-pages` branch, where the current one lives.

**Comment by galvc** [comment]
Hi, I can help by making some design wireframes if that's something you're also looking for?

**Comment by ellisonleao** [comment]
sure @galvc , that would be nice!

**Comment by galvc** [comment]
hi @ellisonleao here are my suggestions

![sjs - frontpage 1](https://user-images.githubusercontent.com/26034240/66673836-50c47a00-ec16-11e9-86e4-52baa932777e.png)
![sjs- frontpage 2](https://user-images.githubusercontent.com/26034240/66673834-502be380-ec16-11e9-9d0b-65ed175656e0.png)
![sjs-compoennts](https://user-images.githubusercontent.com/26034240/66673835-502be380-ec16-11e9-82fb-8f3bad4574a9.png)

**Comment by ellisonleao** [comment]
Liked the clean idea 

some questions:

- Is the left sidebar fixed?
- Can we have a copy to cliboard button in the example inside a `<code>` block or something like it?
- Are you using some specific CSS framework or just custom css?

**Comment by ellisonleao** [comment]
hey @galvc any updates ?

**Comment by arximughal** [comment]
I'd drop-in here and suggest to go with Gatbsy. Great platform. I just finished working on a verrryyy big application using Gatsby.

**Comment by TechiePriyaRanjan** [comment]
I can design website for this. But I want to know, what platform you want ? can I do in HTML or you prefer some platform, like Gatsby , Next.js etc?

**Comment by arximughal** [comment]
I can help with Gatbsy too (in case @ellisonleao decides to go with Gatbsy).

**Comment by galvc** [comment]
> hey @galvc any updates ?

Hi @ellisonleao Very sorry, I got sick and was unable to do this. But my bad, I also am not able to continue because I need time to rest. Thanks for the opportunity to design for this and good luck to everyone else

**Comment by RafaelDavisH** [comment]
I currently exploring with Gatsby and would to love collaborating on this new site project. I can also help with any graphics if needed - I have experience with Photoshop and Illustrator as well.

**Comment by pedrowindisch** [comment]
Hey there,

I'd like to contribute to this project. I designed a logo and a website concept. Feel free to contact me if you liked it - I'm more than happy to answer any questions.

**Logo**
![presentation](https://user-images.githubusercontent.com/30203228/70397869-b9e92380-19f4-11ea-9d25-10324c11a253.png)

**Home**
![Web 1920 – 1](https://user-images.githubusercontent.com/30203228/70397887-d1c0a780-19f4-11ea-9c47-4cf8f6d3c90d.png)

**Getting started page**
![Web 1920 – 2](https://user-images.githubusercontent.com/30203228/70397888-d1c0a780-19f4-11ea-8597-b31654a4ba43.png)

**Components page**
![Web 1920 – 3](https://user-images.githubusercontent.com/30203228/70397889-d1c0a780-19f4-11ea-9ac6-492f44f75b70.png)

**Comment by Togooroo** [comment]
Is this still up for grabs, I would like to make it if it's still available.

**Comment by ellisonleao** [comment]
hey @Togooroo , thanks ! Sure, i am still making my own sketchups here, but feel free to send your ideas.

**Comment by emilkowalski** [comment]
Can I still take it?

**Comment by leanjunio** [comment]
Hey @ellisonleao, also looking to contribute here! Anything that I can do? Or you're still looking for ideas right now?

**Comment by ellisonleao** [comment]
hey @leanjunio thanks for the help! I haven't started it yet, so any ideas will be highly appreciated

**Comment by ShimantaBhuyan** [comment]
Hey @ellisonleao, I too would like to contribute for the new website. Can help in implementing the designs if you've made any.

**Comment by ellisonleao** [comment]
hey @ShimantaBhuyan feel free to send some ideas! thanks

**Comment by ShimantaBhuyan** [comment]
> hey @ShimantaBhuyan feel free to send some ideas! thanks

Sure @ellisonleao
