### ISSUE TITLE
Email example not working

### ISSUE THREAD

**Issue by meowsus** [ellisonleao/sharer.js#106]
I didn't get a chance to dig into this issue, but I wanted to note what I have been seeing.

For me, on Chrome 78.0.3904.97 in Ubuntu 19.10, the [email sharing section](http://ellisonleao.github.io/sharer.js/#email) does not work. No errors in console.

I'm curious if anyone else is experiencing this issue.

**Comment by ellisonleao** [comment]
hey @meowsus do you have the html code you've tried to use?

**Comment by meowsus** [comment]
@ellisonleao Sorry I wasn't more clear. The example on the github.io page doesn't work for me. I double checked in my app and found it, too, wasn't working. So that HTML from the github.io page should suffice for a test scenario.

Great avatar, btw.

**Comment by ellisonleao** [comment]
@meowsus are you using some email client? i am testing on Pop_OS 19.10 with Chromium and the link is working for me.

**Comment by meowsus** [comment]
O-O My mistake, it seems like I can't click on any mailto: links.

![doh](https://i.imgur.com/sEd6unV.gif)

**Comment by ellisonleao** [comment]
np! Glad that you found the issue
