### ISSUE TITLE
Button class

### ISSUE THREAD

**Issue by thejae** [ellisonleao/sharer.js#11]
Instead of using button, i would like to use a div instead

````
<div class="sharer button" data-sharer="twitter" data-title="Checkout Sharer.js!" data-url="https://ellisonleao.github.io/sharer.js/">Share on Twitter</div>
````
This seems to work fine until I remove the `.button` class. Since this conflicts with bootstrap, I don't want to use this class name. Is it possible to user `.sharer` class on its own?

**Comment by thejae** [comment]
Update.

My bad, seems like i had some CSS conflicts.

**Comment by ellisonleao** [comment]
Hey @thejae , did everything went well? Hope to see sharer.js being used on sites.

**Comment by thejae** [comment]
Yes, rather stupid. Some elements had higher z-index and covering the sharer icon.

It's a decent plugin, am surprised it has such a small community activity.

**Comment by ellisonleao** [comment]
Yeah, it is a very new plugin. I hope we can share on more places.
