### ISSUE TITLE
Viber Doesn't Work Anymore

### ISSUE THREAD

**Issue by HoldOffHunger** [ellisonleao/sharer.js#114]
New viber documentation says not to use the URL format as indicated in this repo anymore: https://developers.viber.com/docs/tools/deep-links/

In addition, I have tested out both the old and new URL format.  Neither of them seem to produce any results in testing.  I have made a video of the results: https://www.youtube.com/watch?v=3NHb2J0swZ4&feature=youtu.be

Other URLs are fine.  Can someone else please test this out and tell me if I'm looking at this incorrectly?  Thanks.

**Comment by ellisonleao** [comment]
I still see the current URL format in the [Share Button](https://developers.viber.com/docs/tools/share-button/#setting-up-the-viber-share-button) section. Maybe i am missing something?

**Comment by HoldOffHunger** [comment]
Right, the documentation says it is supported, but my testing shows that it is not supported.  I haven't tested it since 21 days ago, though.

The page tested is sortwords.com (a demo site), with the url `viber://forward?text=sortwords.com`, as you can see from the video, clicking the link merely opens a blank message form in the app.  In that sense, the arguments are irrelevant, if you want to decide to keep it listed.  I'll see if I can test again today.

URL's for me to look at again:

    [viber://forward?text=sortwords.com](viber://forward?text=sortwords.com)
    [viber://forward?text=sortwords.com](viber://forward?title=sortWordsTitle&text=sortwords.com)
    [viber://forward?text=sortwords.com](viber://forward?title=sortWordsTitle)

**Comment by HoldOffHunger** [comment]
Wow, it is impossible to hyperlink Viber links in GitHub.  I'm sure that's not an omen. =)

**Comment by ellisonleao** [comment]
ok i will remove viber for now. If we have a clear definition in the future, we can  always re add it
