### ISSUE TITLE
Digg Doesn't Work Anymore

### ISSUE THREAD

**Issue by HoldOffHunger** [ellisonleao/sharer.js#115]
Hey hey, try this url?  http://www.digg.com/submit

Or this one?  https://digg.com/submit?url=google.com

I'd like to make the fix and adjustment myself, and then submit a pull request.  I just wanted to make sure I'm not totally mistaken here before I do that.

**Comment by metapodcod** [comment]
digg still not working now , I tested it here, it doesn't work in your demo eitherhttps://ellisonleao.github.io/sharer.js/#digg  @ellisonleao @HoldOffHunger
