### ISSUE TITLE
Weibo Doesn't Work Anymore

### ISSUE THREAD

**Issue by HoldOffHunger** [ellisonleao/sharer.js#117]
Wanted to get someone else's opinion on this, if possible.

Weibo's url:

    http://service.weibo.com/share/share.php?url={url}&appkey=&title={title}&pic={image}&ralateUid=

Official source has update this url: https://open.weibo.com/wiki/ShareCode

New format:

    http://vtsina.com.cn/share/share.php?url={url}&appkey=&title={title}&pic={image}&ralateUid=

Test results: The old format gives me a 404, and the new format never connects, because vtsina.com.cn is unreachable.  So, both error out.  Anyone else able to get this to work?

**Comment by ellisonleao** [comment]
http://service.weibo.com/share/share.php is working for me. Can you check again please?

**Comment by HoldOffHunger** [comment]
Oh, wow, it is back!

I very seriously tested the above URL, it's still in my browser history.  But yes, it's definitely working.  Glad I could get another pair of eyes on this!

Thanks for looking and verifying!
