### ISSUE TITLE
Commonjs support

### ISSUE THREAD

**Issue by joseluisq** [ellisonleao/sharer.js#12]
I think it's necessary [Commonjs](http://requirejs.org/docs/commonjs.html) support for using Sharerjs like Nodejs module ([browserify](https://github.com/substack/node-browserify), [Webpack](https://webpack.github.io/), etc) and [Requirejs](http://requirejs.org/) (AMD).

**Comment by ellisonleao** [comment]
Hey @joseluisq  thanks for the feedback. However since that lib does not expose any API, how can a js module could help in this case?

**Comment by joseluisq** [comment]
The reason is because **[npm is for all javascript](http://maxogden.com/node-packaged-modules.html)**, front or backend alike.
In fact, Browserify brings Nodejs modules to client side.

**Comment by joseluisq** [comment]
Here some idea:
```js
const $ = require('jquery');
const sharerjs = require('sharerjs');
const links = $('.sharing-links a');
sharerjs(links);
```

**Comment by ellisonleao** [comment]
hey @joseluisq i am still not conviced this could actually bring some cool stuff to that lib. The reason i've created it is to keep it simple as possible, and i believe creating modules and stuff i will lose that "simplicity".  I will stick with a simple js lib for now, thanks.

**Comment by okmttdhr** [comment]
I created https://github.com/okmttdhr/sharer.npm.js to support CommonJS.
