### ISSUE TITLE
Implement Navigator.share capability

### ISSUE THREAD

**Issue by twf-nikhila** [ellisonleao/sharer.js#121]
I just stumbled on this js library, it's amazing. 

It will be amazing if **Navigator.share()** can be implemented to this, almost no other social media share library has this feature and it will make this unique.

With websites moving toward mobile web & PWA having this is feature is must consider.

For more details check this https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Note:** this works only in mobile and tablet devices.

**Comment by ellisonleao** [comment]
Closing this for now, since we have no plans to add that for now.
