### ISSUE TITLE
Telegram doesn't seem to open up a window

### ISSUE THREAD

**Issue by Sandy-Garrido** [ellisonleao/sharer.js#122]
First of all - thank you sir for a wonderfully simple sharing script.

Telegram - I've got a row of 6 social buttons, all exactly the same, however telegram doesn't open a window.

Looking in console debugger, it looks like it loops through and knows that it's telegram and takes the info from the data tags but can't see what happens after that.

**Comment by ellisonleao** [comment]
hey @Sandy-Garrido thanks for the report. Can you share some of the code you are trying, so i can check on my side please?

**Comment by Sandy-Garrido** [comment]
Sure. I have tried it on your website too and the telegram doesn't load a window.

Below is the HTML which at this point I believe is enough to debug as I've not altered your script & the other buttons work fine.

Please let me know if you'll need anything else

```
            <div id="post-sharer" class="post-share text-right">
            <button data-sharer="facebook" data-url="' . $url . '" title="' . $title . '" class="fab fa-facebook-f"></button>
            <button  data-sharer="twitter" data-url="' . $url . '" data-title="' . $title . '" class="fab fa-twitter"></button>
            <button  data-sharer="pinterest" data-url="' . $url . '" data-title="' . $title . '" class="fab fa-pinterest"></button>
            <button  data-sharer="linkedin" data-url="' . $url . '" data-title="' . $title . '" class="fab fa-linkedin-in"></button>
            <button  data-sharer="xing" data-url="' . $url . '" data-title="' . $title . '" class="fab fa-xing"></button>
            <button data-sharer="telegram" data-url="' . $url . '" data-title="' . $title . '" class="fab fa-telegram-plane"></button>
            </div>
```

**Comment by ellisonleao** [comment]
hey @Sandy-Garrido sorry for the late response. I've able to reproduce it here, but i am waiting to push the fix together with the new code which is coming soon in `0.5.0` by porting the lib to ES6 #123
