### ISSUE TITLE
Port to ECMAScript 6

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/sharer.js#123]

**Comment by Sandy-Garrido** [comment]
Quick question on this. As I've been using the @latest import of your script. 
Will I need to do anything in order for things to continue to run smoothly? If so what as I'm using it in multiple places. 

Many thanks :)

**Comment by ellisonleao** [comment]
Yeah, there will be some hard shifts, since the design has changed a little bit. I will get the specifics documented so everyone stays synced up. The main change is that now the user will have to start the share initialization, since that was the main issue from the current errors.
