### ISSUE TITLE
Sharing using chrome on android opens facebook website not the application

### ISSUE THREAD

**Issue by wr17** [ellisonleao/sharer.js#146]
I am using your library and I have a website when I click on the share on Facebook button it redirects me to the browser, not the native app even I have a Facebook application installed and I am logged in on Facebook.

I have tried Linkedin it opens the app.

**Comment by ellisonleao** [comment]
i believe this is the right behaviour unfortunately. If you have more information on this feel free to open a PR so we can discuss it.

**Comment by MilanBulatovic** [comment]
This is unfortunately still a problem. Still open browser. Any chance to be fixed?
