### ISSUE TITLE
Telegram button does not work

### ISSUE THREAD

**Issue by k0fi** [ellisonleao/sharer.js#167]
Hello Ellison,
I'm using minified version of `@version 0.4.1`. All work but the telegram button does not open telegram web:

```
<button class="my-btn" data-sharer="telegram" data-title="My Awsome photo!" data-url="https://mysite/path/to/photo.gif" >
   <img class="img-responsive" src="/static/telegram.svg">  
</button>
```

I tried the tag with `data-to="+44555-5555"` but that did not help.
I also tried `sharer.min.js version 1.0` . That did not work either. 

Am I missing something or the API has changed?

**Comment by ellisonleao** [comment]
hey @k0fi , for telegram web you need to pass the `data-web=true` param. Can you check if that works for you? sorry if the docs are not clear, we still need to update it
