### ISSUE TITLE
Getting server ip over address when sharing on Facebook

### ISSUE THREAD

**Issue by vedovato** [ellisonleao/sharer.js#17]
Hey, i'm trying to share my content on Facebook with sharer.js + meteor with spiderable and when i hit the share btn, i just got Facebook trying to fetch data from my ip instead my domain and i never get the right image. Below my spiderable settings:

```
Template.frontArticleSingle.onCreated(function(){
  var self = this;
  self.autorun(function(){
    var slug = FlowRouter.getParam('slug');
    self.subscribe('artigoSingleHome', slug, {onReady: function() {
      var pagina = Artigos.findOne({ slug: slug });
      SEO.set({
        title: 'Sindicond - ' + pagina.titulo,
        description: pagina.conteudo,
        meta: {
          'property="og:title"': pagina.titulo,
          'property="og:site_name"': 'Sindicond',
          'property="og:description"': pagina.resumo,
          'property="og:image"': pagina.imagem,
          'property="og:image:type"': 'image/jpeg'
        }
      });
    }});
  });
});
```

**Comment by ellisonleao** [comment]
Hey @vedovato , looks like this is an issue with the SEO lib adding the wrong host inside the og tags. Can you check those tags when the page is rendered? sharer.js only redirects to `data-url` attribute and facebook fetches the info from that url

**Comment by vedovato** [comment]
Thank you @ellisonleao. I'm gonna check it later :)

**Comment by ellisonleao** [comment]
Any updates, @vedovato ? Can we close this issue?

**Comment by ellisonleao** [comment]
Closing this issue. If you have any extra issues, please feel free to open again!
