### ISSUE TITLE
Email data attribute not working!

### ISSUE THREAD

**Issue by herrseiler** [ellisonleao/sharer.js#180]
Recently I noticed that the share with email function no longer works. You press the button and nothing happens! Even on your doc website it doesn't open the mail client work.

`<button class="button" data-sharer="email" data-title="Awesome Url" data-url="https://ellisonleao.github.io/sharer.js/" data-subject="Hey! Check out that URL" data-to="some@email.com">Share via Email</button>`

Thanks!

**Comment by ellisonleao** [comment]
hey @herrseiler i've just tested it in the docs page and I got redirected in my gmail account for a new email msg. What browser are you using?
