### ISSUE TITLE
Skype and Quora errors

### ISSUE THREAD

**Issue by ghnp5** [ellisonleao/sharer.js#202]
Sharing to Skype:

![image](https://user-images.githubusercontent.com/57591332/132113010-32475d56-371d-42df-8585-412a6d8f9ca3.png)

Sharing to Quora:

![image](https://user-images.githubusercontent.com/57591332/132113018-2588777c-2769-4a42-b920-6ca1bd80724a.png)

**Comment by ellisonleao** [comment]
Quora is now removed and Skype seems to be working now. Please reopen if the issue remains
