### ISSUE TITLE
WhatsApp redirects to the whatsapp website instead of opening a popup

### ISSUE THREAD

**Issue by 3PSY0N** [ellisonleao/sharer.js#219]
Hello,

As the title says, WhatsApp redirects to the whatsapp website instead of opening a popup, and the user has to click on the browser back button to return to my website.

Thanks!

**Comment by 3PSY0N** [comment]
OK, i didn't understand the parameter `IsLink` for some services.
Can we pass isLink as bool barameter somewhere?

**Comment by ellisonleao** [comment]
hey @3PSY0N how are you defining the sharer HTML element?

**Comment by barnes-killianH** [comment]
Hello @3PSY0N i have the same probleme with whatsapp. I apply this modification. In library sharer.js you have have a test in prperty isLink

`if (!sharer.isLink) {
        var popWidth = sharer.width || 600,
          popHeight = sharer.height || 480,
          left = window.innerWidth / 2 - popWidth / 2 + window.screenX,
          top = window.innerHeight / 2 - popHeight / 2 + window.screenY,
          popParams = 'scrollbars=no, width=' + popWidth + ', height=' + popHeight + ', top=' + top + ', left=' + left,
          newWindow = window.open(sharer.shareUrl, '', popParams);
          alert(sharer.shareUrl)

        if (window.focus) {
          newWindow.focus();
        }
      } else {
        window.location.href = sharer.shareUrl;
      }`

If propertry is false also your link open in your page and not in popup. For open whatsapp in popup you just modifie property isLink by false in configuration of whatsapp

` whatsapp: {
            shareUrl: this.getValue('web') !== null ? 'https://api.whatsapp.com/send' : 'https://wa.me/',
            params: {
              text: this.getValue('title') + ' ' + this.getValue('url'),
            },
            isLink: false,
          },`

**Comment by barnes-killianH** [comment]
> Hello @3PSY0N i have the same probleme with whatsapp. I apply this modification. In library sharer.js you have have a test in prperty isLink
> 
`if (!sharer.isLink) {
        var popWidth = sharer.width || 600,
          popHeight = sharer.height || 480,
          left = window.innerWidth / 2 - popWidth / 2 + window.screenX,
          top = window.innerHeight / 2 - popHeight / 2 + window.screenY,
          popParams = "scrollbars=no, width=" + popWidth + ", height="+ popHeight + ", top=" + top + ", left=" + left,
          newWindow = window.open(sharer.shareUrl, "", popParams);

        if (window.focus) {
          newWindow.focus();
        }
} else {
  window.location.href = sharer.shareUrl;
}`
> `if (!sharer.isLink) {var popWidth = sharer.width || 600,popHeight = sharer.height || 480,left = window.innerWidth / 2 - popWidth / 2 + window.screenX,top = window.innerHeight / 2 - popHeight / 2 + window.screenY,popParams = "scrollbars=no, width=" + popWidth + ", height="+ popHeight + ", top=" + top + ", left=" + left, newWindow = window.open(sharer.shareUrl, "", popParams); if (window.focus) {newWindow.focus();}} else { window.location.href = sharer.shareUrl;}`
> 
> If propertry is false also your link open in your page and not in popup. For open whatsapp in popup you just modifie property isLink by false in configuration of whatsapp
> 
> ` whatsapp: {shareUrl: this.getValue('web') !== null ? "https://api.whatsapp.com/send" : "https://wa.me/",params: {text: this.getValue('title') + "" + this.getValue("url"),},isLink: false,},`

**Comment by ellisonleao** [comment]
The original whatsapp sharer element is considered to be a link on all times, that's why it doesn't support opening the web link in a popup for now.  I will think about something but for now you can just try removing the [`isLink`](https://github.com/ellisonleao/sharer.js/blob/main/sharer.js#L112) here value here and use a custom code until i think in a fix

**Comment by 3PSY0N** [comment]
Hello, thank you for reply, i use custom code for now, for exemple:

A temporary solution
```js
whatsapp: {
    shareUrl: this.getValue('web') !== null ? 'https://api.whatsapp.com/send' : 'https://wa.me/',
    params: {
        text: this.getValue('title') + ' ' + this.getValue('url'),
    },
    isLink: this.getValue('islink') ? this.getValue('islink') : false,
},
```
Can be used with `data-islink="true|false"` 

And for the html part
```html
<button class="shareBtn" data-islink="true" data-sharer="whatsapp" data-title="Hi there! Check this post!" data-url="{{ site_url ~ '/' ~ post.slug }}">
    <svg>SVG Icon</svg>
    <span>WhatsApp</span>
</button>
```

It's working for now.

Tell me if it's viable or not.

Thank you!

**Comment by luis-fonseca** [comment]
Maybe it would be interesting to give the possibility to open in a new tab

**Comment by luis-fonseca** [comment]
@ellisonleao 

I needed to change how your library works for a project, so I added a data newTab attribute. Also, I made a change at the end of the script.

` <a href="#" data-sharer="whatsapp" data-title="Checkout Sharer.js!"
        data-url="https://ellisonleao.github.io/sharer.js/" data-web="data-web" data-new-tab="true">Whatsapp <i
          class="fab fa-whatsapp"></i></a>`

```javascript
if (sharer.newTab) {
  window.open(sharer.shareUrl, '_blank');
} else if (!sharer.isLink) {
  var popWidth = sharer.width || 600,
    popHeight = sharer.height || 480,
    left = window.innerWidth / 2 - popWidth / 2 + window.screenX,
    top = window.innerHeight / 2 - popHeight / 2 + window.screenY,
    popParams = 'scrollbars=no, width=' + popWidth + ', height=' + popHeight + ', top=' + top + ', left=' + left,
    newWindow = window.open(sharer.shareUrl, '', popParams);

  if (window.focus) {
    newWindow.focus();
  }
} else {
  window.location.href = sharer.shareUrl;
}
```

**Comment by ellisonleao** [comment]
@luis-fonseca yep that's the idea, i will implement it soon and let you guy know

**Comment by ellisonleao** [comment]
New version was pushed. To create a sharer as link you can use now:

```html
<button class="button" data-sharer="whatsapp" data-web=true data-link=true data-blank=true data-title="Checkout Sharer.js!" data-url="https://ellisonleao.github.io/sharer.js/">Share on Whatsapp</button>
```

where: 
- data-web - will point the share to whatsapp web (remove if you want the old behaviour)
- data-link - will convert the sharer behaviour into a link
- data-blank - will make the link open the link in a new tab

Make sure to update to 0.5.0 version
