### ISSUE TITLE
Linkedin Sharing "Something went wrong"

### ISSUE THREAD

**Issue by crowebar** [ellisonleao/sharer.js#224]
When attempting linked in sharing get the "Something went wrong" message

![Screen Shot 2022-01-30 at 6 00 00 pm](https://user-images.githubusercontent.com/25500327/151690093-11eff427-2dc1-4464-acf3-016d3d88c702.png)

I think the linked in sharing URL has changed...
https://www.linkedin.com/sharing/share-offsite/?url={url}

https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/plugins/share-plugin

**Comment by ellisonleao** [comment]
@crowebar thanks for the report! will update it

**Comment by ellisonleao** [comment]
hey @crowebar that url is still being used at end in the current URL. Maybe something wrong with your test URL?
![Screenshot from 2022-02-01 13-48-09](https://user-images.githubusercontent.com/178641/152012841-48adf172-ab1a-449b-b6c6-548699bca48c.png)

**Comment by crowebar** [comment]
I'll do some more testing, thanks
