### ISSUE TITLE
Random error in meteor.js

### ISSUE THREAD

**Issue by nubestra** [ellisonleao/sharer.js#23]
sometimes everything works fine
i reloaded several times the webpage and found that sharer dont always work

i see this error on browser terminal
Uncaught TypeError: Cannot read property 'index' of undefined (firefox)
Uncaught TypeError: Cannot read property 'index' of undefined (google chrome)
Uncaught SecurityError: Blocked a frame with origin "https://www.youtube.com" from accessing a frame with origin "http://localhost:3000".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match. (google chrome)

i see this errors and the sharer button doesnt work

**Comment by ellisonleao** [comment]
hey @nubestra do you have a piece of your code so we can investigate?

**Comment by nubestra** [comment]
sure @ellisonleao i have a private git, i can invite you so you can have a look

**Comment by nubestra** [comment]
I think sometimes work because meteor fires the script before the template is rendered, thats why i see "undefined" we need to find a way for the script to wait for template to be rendered and after that launch the script, will continue searching for the solution

**Comment by ellisonleao** [comment]
fixed on repo.
