### ISSUE TITLE
Are you using sharer.js? Let me know!

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/sharer.js#24]
I will leave this issue opened for anyone who wants to talk about using sharer.js on your projects. Feel free to give us some feedback!

**Comment by nubestra** [comment]
mole.meteor.com check it out

**Comment by leafiy** [comment]
Very helpful! Considering to use! Could you add Weibo support?

**Comment by Abhinav1217** [comment]
Hi, Nice script. Is there a way to add a logo/icon-font in the button. Something like `data-logo='path to image'` or `data-logo='icon-font-character'` . 
Not looking for a complete _battries included_ package, just a simple way to tell it to use an Icon.

**Comment by ellisonleao** [comment]
hey @leafiy , just opened #30 . Let's move the discussion to there.

hey @Abhinav1217 can you explain this a little bit more? I believe for styles you could simple use CSS.

**Comment by JoshuaDoshua** [comment]
Was, but stopped since the commercial license.

**Comment by TrnsltLife** [comment]
Hey, I just bought the single use commercial license to use on the tutorial pages on www.CommentHow.com. I like that it's lightweight, covers a lot of services, and it's worth the $9 for me not to have to write it myself. Thanks!

P.S. I modified the .js on my server to include image and description to pinterest. Can you add that to your version?

```
                    pinterest: {
                        shareUrl: 'https://www.pinterest.com/pin/create/button/',
                        params: {
							url: this.getValue('url'),
							description: this.getValue('caption'),
							media: this.getValue('image')
						}
                    },
```

**Comment by ellisonleao** [comment]
hey @TrnsltLife , thanks for sharing! will update it soon. Thanks

**Comment by JoshuaDoshua** [comment]
Question, are you going to give @TrnsltLife some kind of kickback since he paid $9 and contributed to your repo (and essentially profits)?

**Comment by neuropass** [comment]
Hi,

terrific plugin, finally! yes, +1 @TrnsltLife for rich pins..
purchasing the license to support the project.

question, would it be possible to use a bootstrap 3.1.x modal rather then the default browser tab? can it be done?

**Comment by ellisonleao** [comment]
Hey @neuropass , that can be done, but unfortunately we will need to override the default's `window.open` method to use a modal, which will add a dependency to the project. I really want to keep this lib as simple as possible for now. I think we can extend this project and make another ones, like `sharer.bootstrap.js`,  `sharer.jquery.js` , etc..

**Comment by neuropass** [comment]
I think extending it would be terrific. At least for Bootstrap :) :+1:

**Comment by jshwlkr** [comment]
http://dme.engin.umich.edu/northcampus-minecraft/
Giving it a try here, hoping to get it adopted as an alternative to AddThis.

**Comment by arximughal** [comment]
just created a small sharer.css extension for this plugin to make the share button more beautiful and modern. Check it out [here](https://github.com/arximughal/sharer.js-with-css)

**Comment by godban** [comment]
@arximughal demo?

**Comment by ellisonleao** [comment]
@arximughal nice one! thanks

**Comment by arximughal** [comment]
@godban will be sharing soon. Just gotta do a little bit housekeeping :P ;)

**Comment by arximughal** [comment]
@ellisonleao Pleasure. :)

**Comment by arximughal** [comment]
@godban here's the demo https://arximughal.github.io/sharer.css/

**Comment by optimusvish** [comment]
@ellisonleao Hi, I'm using this script on my project but it's not working on ajax loaded content. Can I get any help to solve this?? Thanks anyway for this script.

**Comment by ellisonleao** [comment]
hey @optimusvish can you open a new issue so we can discuss it please?

**Comment by paulohrpinheiro** [comment]
Hello Ellison! Now I am also using: https://paulohrpinheiro.xyz, thank you!

**Comment by dgmariscal** [comment]
Hi Ellison! I using in all of my projects since i discover you jajaja, your script is very helpfull, Thanks You A Lot!!.

**I Have a Question:** in some project i been working, is a web app version of a magazine client, all work correct, but the client ask me if like you share in Whatsapp, the browser ask if you like to open the app for send the share message, we can do the same if i have facebook app and twitter app in my phone. Is this Posible?

Thanks again, i hope you can help me. (k)

**Comment by optimusvish** [comment]
@dgmariscal replace this code
`facebook: {
                        shareUrl: 'https://www.facebook.com/sharer/sharer.php',
                        params: {u: this.getValue('url')}
},`
with below
facebook: {
                        shareUrl: 'fb://publish/',
                        params: {text: this.getValue('url')}
},
and check once.

**Comment by dgmariscal** [comment]
thanks @optimusvish looks fine, do you know what are the shareUrl for the same thing but for Twitter app?

**Comment by optimusvish** [comment]
@dgmariscal there is no need to change the URL for twitter. If u have installed the twitter app it'll automatically share in app.

**Comment by dgmariscal** [comment]
@optimusvish thanks, i don't have installed the official twitter app, my bad jaja

**Comment by dgmariscal** [comment]
Hi @optimusvish, i change the code for share with facebook app, but some days ago this don't work, open the FB app but don't open the publish windows, what do you think is happening? .

The url is: m.codigomagenta.com.mx

Thanks in advance

**Comment by ellisonleao** [comment]
Hey guys, sharer.js is now using a MIT License and it's going to be free forever! 😄 

Feel free to share , modify and use it.  Just let me know if it goes well!

**Comment by rebornishard** [comment]
@ellisonleao dude please change email share data component, it's kinda annoying to enter email to,
it's possible to change it with email from, so user only need to fill up who he will share it (possible for multiple email share)
thanks for a great project

**Comment by ellisonleao** [comment]
hey @rebornishard not sure if i follow. Are you saying that the `To:` field is not being populated properly?

**Comment by rebornishard** [comment]
@ellisonleao ok sir, i'll change to trollid account, since i'll using sharer.js on it

**Comment by sevasargsyan** [comment]
Hi! Ok.ru noth working.

**Comment by ellisonleao** [comment]
@fadlurss facebook uses `data-hashtag` instead of `data-hashtags` .  What is the error you are getting?

**Comment by am0nshi** [comment]
https://aftership.com.ua/ 👍

**Comment by ellisonleao** [comment]
Closing this since github now has a "Used By" button

**Comment by alexlugouv** [comment]
Hi @ellisonleao, good job :)
Is it possible to remove the console.log when click on the Email button ?

Thank you

**Comment by ellisonleao** [comment]
hey @alexlugouv we dont have any console msgs in the bumped code. What version are you using?

**Comment by alexlugouv** [comment]
> hey @alexlugouv we dont have any console msgs in the bumped code. What version are you using?

@ellisonleao, on https://ellisonleao.github.io/sharer.js/, when I click on Share via Email on Email block.

**Comment by aledocdonnini** [comment]
Is it possible to use the same button twice to share the same url but with different anchor ids?

**Comment by marcoangelo** [comment]
@ellisonleao Using on www.meditationtimer.online Thanks!
