### ISSUE TITLE
Possibility to share an image in data URI scheme

### ISSUE THREAD

**Issue by bacloud23** [ellisonleao/sharer.js#247]
Hi, Thanks Ellison for providing this library !

Is it possible to share an image ? preferably having `data:image` ?

I already saw in examples for sharing on **Buffer** you are setting `data-picture` but I couldn't understand what's that about .

thanks

**Comment by ellisonleao** [comment]
hey @bacloud23 not sure if any providers accepts base64 images due to security reasons, the current ones that accept `data-picture` params are using URLs
