### ISSUE TITLE
Change Twitter to X?

### ISSUE THREAD

**Issue by tboggia** [ellisonleao/sharer.js#270]
## Issue Description
Twitter is (whyyyy) now X. Have a preference on how to address this?

I'm needing to add stuff like this which is not the end of the world, but also not ideal: `data-sharer="{{ $social['name'] == "x" ? "twitter" : $social['name'] }}"`

## Proposed Solution
Not sure if this is the cleanest solution, but it should work:
sharer.js:418:
418:  - s = sharers[sharer];
418:  + s;
419:  + sharers.x = sharers.twitter;
420:  + s = sharers[sharer];

<img width="351" alt="image" src="https://github.com/ellisonleao/sharer.js/assets/17348237/5d25e1c5-ccc9-463f-a571-9836b5b49c69">

**Comment by ellisonleao** [comment]
nah, i like the old name. Doesn´t hurt to still use it as the sharer name.
