### ISSUE TITLE
Bower package name

### ISSUE THREAD

**Issue by sylvainbaronnet** [ellisonleao/sharer.js#32]
Hi,
Can you tell me why the name is `sharerjs` in the bower command line but the bower package name is `sharer.js` ?

This cause me an issue with a script I use to automatize bower package install / uninstall.
I made a special case for this package but I'd rather not...

Thanks

**Comment by ellisonleao** [comment]
Nothing special, i can change if its causing troubles. Thanks for reporting!

**Comment by ellisonleao** [comment]
Just registered the new one.  You can now install with  `bower install sharer.js`

**Comment by sylvainbaronnet** [comment]
Great ! Thank you very much
