### ISSUE TITLE
Popup width too small for pinterest (login form)

### ISSUE THREAD

**Issue by sylvainbaronnet** [ellisonleao/sharer.js#33]
Hi,

The popup for pinterest is too small if you're not logged in :

![screen shot 2016-02-20 at 16 24 34](https://cloud.githubusercontent.com/assets/1569516/13197467/b8ec9238-d7ee-11e5-8e2b-c49a34a2c787.png)

Edit: the login button is hidden (top right)

**Comment by ellisonleao** [comment]
hey @sylvainbaronnet i am adding a custom `data-width` and `data-height` to solve this issue. Unfortunately we can't check if the user is logged in before opening the popup, without adding a lot of dependencies. If you want to increase your sharer pop simply add

```html
<button class="sharer" data-sharer="yoursharer" data-width="800" data-height="600" ... >Awesome!</button>
```

Note this is from the `0.2.13>` version.

**Comment by sylvainbaronnet** [comment]
Perfect, thank you
