### ISSUE TITLE
Add pull information from Open Graph (OG) Meta Tags

### ISSUE THREAD

**Issue by neuropass** [ellisonleao/sharer.js#38]
Can you add a global data- option that pulls the site info from Open Graph (OG) Meta Tags ?

For example the title, description , and image as the very basics.

**Comment by ellisonleao** [comment]
Not sure if i follow your proposal. when you are sharing a content , the sharer social network will automatically fetch the og tags and populate the image/description with their contents. Some of them accepts a custom image, description and title.

**Comment by neuropass** [comment]
Maybe I misunderstood the plugin usage then. 
If use this as the example shows:
`<button class="sharer button" data-sharer="twitter" data-title="Checkout Sharer.js!" data-hashtags="awesome, sharer.js" data-url="https://ellisonleao.github.io/sharer.js/">Share on Twitter</button>`

will only share the url, title and the hashtag. but if in my page there is an image or some other og tags like published time etc those will not be included in the shared button.
or ma I missing something?

**Comment by ellisonleao** [comment]
Yes, they will be included too if provided on the `og:tags` . On twitter case you can also have the twitter cards, which is specific for twitter posts. Please take a look at https://dev.twitter.com/cards/overview

**Comment by neuropass** [comment]
Gotcha. Ok I completely miss-read it then. I thought you would just indicate what to share via data- attribute. Then if it fetches wherever meta tags are present in the page is perfect :)

**Comment by ellisonleao** [comment]
Nice! Will close this one then.

**Comment by neuropass** [comment]
Ok I see. so that depends on the social media itself then and not the plugin? Its confusing because on facenbook and pinterest you see the picture erc in the share box but not with the other networks. 
sorry for insisting on this, I just wanted to be sure.
