### ISSUE TITLE
How to add social counter?

### ISSUE THREAD

**Issue by armbull** [ellisonleao/sharer.js#46]
Hello,
How to add social counter for social buttons. I have this code `countUrl:"https://graph.facebook.com/?id={url}&access_token={accessToken}&callback={callback}",countCallback:function(t){return(t.share||{}).share_count||0}}`
And I don't know how to insert it to sharer script and send it to html div.
Thank you.

**Comment by ellisonleao** [comment]
I will think about some generic solution that could be used for the others shares and let you know.

**Comment by armbull** [comment]
I found nice minify solution =) where many counts are released in yandex.tech.
[https://yastatic.net/share2/share.js](url)
There are more social media on it [https://tech.yandex.ru/share/](url)
Please, whatch it and maybe you can add this feature to your script

**Comment by armbull** [comment]
Also you can see as inspiratiob from [https://github.com/sapegin/social-likes/blob/master/src/social-likes.js](here) Social Likes on Github. There are counters. And code is similar as you, a bit)

**Comment by ellisonleao** [comment]
Hey @armbull i did some thinking about this card and i am not having plans for it since some of the sharer sites had the social counter apis removed.
