### ISSUE TITLE
Sharer.js not compatible with Turbolinks

### ISSUE THREAD

**Issue by ssoulless** [ellisonleao/sharer.js#47]
Im trying to use Sharer.js in my Rails app that uses Turbolinks, but it just doesn't work, I have to reload the page... any idea how you can make this plugin compatible with Turbolinks?

**Comment by ellisonleao** [comment]
Hey @ssoulless i don't have any experience with Turbolinks. Do you have a piece of code so we can see what's happening. Just remember that the current sharer code only adds the share handler on the `load` event listener

**Comment by ssoulless** [comment]
Alright, I will make PR, I know how to make this plugin compatible with Turbolinks
