### ISSUE TITLE
Facebook closes Android Chrome while share dialog opens

### ISSUE THREAD

**Issue by yamsellem** [ellisonleao/sharer.js#50]
I've been struggling for several days with facebook sharing dialog on android.

I know this is not directly related to this `sharer` library, but because you've got some experience & feedback with the thing, you may help me a lot.

The thing is, when I open a facebook share dialog on android chrome (with facebook try yourself or with sharer's link), the chrome closes automatically or, if it don't close, every buttons (friends, position, page selection & co) are not working.

This is happening on Android 6.0.x, Chrome 57.0.2987.132
This does not happens on Firefox (52.0.2).

This is happening with every Android phone I have tested.
Thanks a lot.

**Comment by RozbehSharahi** [comment]
I'm not sure if it is related, but for me it closed on chrome (desktop), when the defined data-url was not a valid url. Maybe it helps.

Regards

**Comment by ellisonleao** [comment]
Before the facebook sharer page can be rendered, facebook validates the URL. If the URL is not valid it calls [this url](http://facebook.com/dialog/return/close?error_code=100&error_message=href+should+represent+a+valid+URL#_=_), which closes the modal. Maybe your URL is not valid?
