### ISSUE TITLE
Why am I getting "...Cannot read property 'init' of undefined(…)" when I hit my share button?

### ISSUE THREAD

**Issue by vincentasea** [ellisonleao/sharer.js#51]
Installed the Sharer.js package for Meteor via the atmosphere page. I keep getting this error message when ever I hit a shared button:

 `VM6113:1 Uncaught TypeError: Cannot read property 'init' of undefined(…)`

I get the the exact same error message when I run this in the chrome console: 

`window.Sharer.init();`

Any idea on how I can get it to work?

**Comment by ellisonleao** [comment]
hey @vincentasea can you share some code so i can try to understand the issue?

**Comment by vincentasea** [comment]
Hey there @ellisonleao. Sure thing, find below my events code:

I installed your package via atmosphere using:

**meteor add ellisonleao:sharerjs**

My HTML code:
`<a href="#"> <span class="sharer" >Sharer</span>  </a>`

When I click the Sharer link, it triggers the click .Sharer Template events. Find the code below:
`Template.detail.events({
	
     "click .sharer": function() {
 	//add new buttons with share behaviour
	$('.postedImagesWell').append(<button class="sharer button" data-sharer="facebook" data-url="https://ellisonleao.github.io/sharer.js/">Share on Facebook</button>);
										 			 
       window.Sharer.init();
});
`
And this is the error message I see in the chrome browser console:

**Uncaught ReferenceError: React is not defined**

**Comment by vincentasea** [comment]
Any help would be greatly appreciated

**Comment by ellisonleao** [comment]
This is a different error from the one you've mentioned before. Are you still having errors with the `init` function? how are you adding the sharer.js `<script>` tag? is this a meteor app?

**Comment by vincentasea** [comment]
Hi, Yes its a different error from the one I first had. 
For some reason I am not getting the `init` error anymore. 

Yes Its an Meteor app, so I added the sharer package via atmosphere using `meteor add ellisonleao:sharerjs`.

Looking forward to your help

**Comment by vincentasea** [comment]
Hello there ellisonleao. Kindly help me..

**Comment by ellisonleao** [comment]
Hey @vincentasea sorry for the late response, i was on vacations.

About your problem, the meteor package is not being updated anymore. You should get the latest using `meteor npm install sharer.js` or using the [cdn url](http://www.ellison.rocks/sharer.js/#installing) directly on your template
