### ISSUE TITLE
Media Email and Facebook

### ISSUE THREAD

**Issue by trollid** [ellisonleao/sharer.js#52]
Hello @ellisonleao , as your suggestion, i'll make a new issue here

first :
it's a suggestion for email, can we change data-to into data-from
because if someone ( call this one A ) want to share foo from a web to his friend ( call this one B )
A must remember B email, and input it in input box, so javascript or form can populate data-to
but it's more better if A input his email in data-form or that web can put something like share@web.test into data-from , after that thunderbird or outlook open, A only need to type B name, let the software generate his friend email, some email make itself hard to remember

second :
when i use facebook, it told me : Sorry, this feature isn't available right now: An error occurred while processing this request. Please try again later.

thanks for great project :)

**Comment by suadhuskic** [comment]
@trollid 
If I'm understanding this correctly; you want to set the `from` header ?
That is not possible when using a `mailto` link.

This is not using some crazy email API like lets say PHPMailer; it simply opens a new window using `mailto`.

Here are the possible options to pass when using a `mailto` link:

[https://yoast.com/dev-blog/guide-mailto-links/](https://yoast.com/dev-blog/guide-mailto-links/)

**Comment by ellisonleao** [comment]
@suadhuskic just pretty much answered why this is not possible. Thanks for the issue anyway.
