### ISSUE TITLE
Update jsDelivr links

### ISSUE THREAD

**Issue by LukasDrgon** [ellisonleao/sharer.js#55]
[jsDelivr switched to a fully automated system](https://www.jsdelivr.com/features), that can serve files from npm and GitHub. This means all future releases will be available automatically, but will use a new link structure.

I noticed that there are old links at http://www.ellison.rocks/sharer.js/, the correct link is https://cdn.jsdelivr.net/npm/sharer.js@latest/sharer.min.js.

You can find links for all files at https://www.jsdelivr.com/package/npm/sharer.js.

Feel free to ping me if you have any questions regarding this change.

**Comment by ellisonleao** [comment]
Thanks @LukasDrgon , i've updated it.
