### ISSUE TITLE
How to confirm social share was completed (question)  

### ISSUE THREAD

**Issue by jasan-s** [ellisonleao/sharer.js#56]
I wanted to use this lib to allow my app users to share some app content and in return I wanted to offer them discount code. So my question is how can I check for if the user successfully posted on the respective social platform so I issue a discount code.

**Comment by suadhuskic** [comment]
@jasan-s it is not possible. The lib basically opens the URL and passes all the parameters as GET parameters. There is no callback to this library to check if the user actually did share.

What you want to use is the actual FB SDK. See here:
[https://developers.facebook.com/docs/javascript/](https://developers.facebook.com/docs/javascript/)

**Comment by ellisonleao** [comment]
hey @jasan-s , @suadhuskic pretty much answered the question. If you need some action after the share, you will need to check if the social media you want that action has the ability to do so in another way that is not covered with this lib.
