### ISSUE TITLE
Doesn't position correctly in zoomed windows

### ISSUE THREAD

**Issue by jtuds** [ellisonleao/sharer.js#57]
When using on a zoomed out window or for example a window in Chromes responsive mode emulating a large screen, the popup doesn't open in the center. Depending on how much the screen is zoomed out or how much bigger the emulated screen is than the actual screen determines how far from the center the popup appears.

For example the actual width of the browser on my screen is 1440. When using the emulator to show the screen at 4330, the popup opens far off to the right on my other monitor.

I think the top and left properties of window.open are relative to the window outer dimensions and not the inner. The script uses inner width and height to make its calculation of where to put the popup, but this is not relative to the actual window width and height.

From some brief resarch (https://stackoverflow.com/questions/57652/how-do-i-get-javascript-to-open-a-popup-window-on-the-current-monitor) it doesn't sound like something super easy to solve.

**Comment by jtuds** [comment]
Is this fixed by a PR?

**Comment by ellisonleao** [comment]
hey @jtuds i am not sure this is a huge bug to be concerned right now and i think it's not worth the effort to fix this right now.
