### ISSUE TITLE
Consider using the data-sharer attribute as the selector instead of class .sharer

### ISSUE THREAD

**Issue by soluml** [ellisonleao/sharer.js#58]
Changing [L27](https://github.com/ellisonleao/sharer.js/blob/master/sharer.js#L27) from `var elems = document.querySelectorAll('.sharer'),` to `var elems = document.querySelectorAll('[data-sharer]'),` relieves users from having to add a sharer class to any element they want to act as a share button.

`data-sharer` is a required attribute for all social sharing anyway, so it can be used to kill two birds with one stone here.

**Comment by ellisonleao** [comment]
nice idea @soluml ! Will check it soon. Thanks for the tip
