### ISSUE TITLE
Add support for Whatapp web

### ISSUE THREAD

**Issue by Probocop7** [ellisonleao/sharer.js#59]
Currently I can only get a whatsapp share dialog to open using a mobile device, with the app installed.

On a desktop, clicking the Whatsapp button does nothing. It'd be great if it would use Whatsapp web in this case:

i.e.

`https://web.whatsapp.com/send?text=some text`

**Comment by demetriuschar** [comment]
A quick fix is Changing lines 103 to 109 form: 
`                    whatsapp: {
                        shareUrl: 'whatsapp://send',
                        params: {
                            text: this.getValue('title') + ' ' + this.getValue('url')
                        },
                        isLink: true
                    },`
to 
` whatsapp: {
                        shareUrl: 'https://api.whatsapp.com/send',
                        params: {
                            text: this.getValue('title') + ' ' + this.getValue('url')
                        }
                    },
`
Solves your issue and works for both desktop and mobile
