### ISSUE TITLE
Add support for facebook hashtags

### ISSUE THREAD

**Issue by hacknug** [ellisonleao/sharer.js#61]
Given Facebook supports passing a hashtag parameter to the url, I think it would be a good idea to add support for those on the library.

I can take a look at it if you'd like me to open a PR.

**Comment by mattbag** [comment]
@ellisonleao Hello! Using the latest now, it gives an error if no hashtag is set!

**Comment by ellisonleao** [comment]
hey @mattbag thanks for the tip! will check that out!
