### ISSUE TITLE
Doesn't work for WhatsApp :(

### ISSUE THREAD

**Issue by ProUnebit** [ellisonleao/sharer.js#68]
I am not sure, perhaps it isn't your code problem. But for me your WhatsApp API doesn't work.
However, others soc. net. share buttons works perfectly.

**Comment by ysn47** [comment]
for using in whatsapp web add this to sharer.min.js and set the data-sharer attribute as "whatsappweb"

            whatsappweb: {
                        shareUrl: "https://api.whatsapp.com/send",
                        params: {
                            text: this.getValue("title") + " " + this.getValue("url")
                        }
                    },

this solution works for me.

**Comment by ellisonleao** [comment]
New version (0.3.6) adds a `data-web` attribute with the option to share on whatsapp web. Check [latest docs](http://ellisonleao.github.io/sharer.js/#whatsapp) on how to use
