### ISSUE TITLE
Twitter cards with image  

### ISSUE THREAD

**Issue by SomahCorp** [ellisonleao/sharer.js#73]
Hi there !
1st of all, thank you for this script. I've seen around the web that twitter can share images and video with "Twitter cards". Didn't see this option on your script. Maybe I missed it, but if i've not, do you know how to do such thing with your script ?
Thank you again for your great work !

**Comment by ellisonleao** [comment]
Hey @SomahCorp , the twitter cards works with html meta tags, something like:

```html
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@site_username">
<meta name="twitter:title" content="Top 10 Things Ever">
<meta name="twitter:description" content="Up than 200 characters.">
<meta name="twitter:creator" content="@creator_username">
<meta name="twitter:image" content="http://placekitten.com/250/250">
<meta name="twitter:domain" content="YourDomain.com">
```

The only way you can share an image using this lib right now is that if you just put the image URL inside the `data-url` field:

```html
<button class="button" data-sharer="twitter" data-title="Checkout Sharer.js!" data-hashtags="awesome, sharer.js" data-url="https://mysite.com/image.jpg">Share on Twitter</button>
```
Which might not work as you expect.

**Comment by SomahCorp** [comment]
Thank you for you reply. Problème is, this just add the image path to the tweet instead of building a Twitter card.
I added `<meta name="twitter:card" content="summary_large_image">` in `<head>` which validate the Card on the [Twitter Card Validator](https://cards-dev.twitter.com/validator). 
With a static twitter:image tag, it works perfectly. But to display the selected image, it seems I need to add the _twitter:image_ tag server-side on click an generate them with different image path depending on the link that was clicked. The only languages I know are HTML, CSS, JS and I think I have to do it with Php. If you have any idea, i think it would be a great feature for your work.
