### ISSUE TITLE
style fixes on http://ellisonleao.github.io/sharer.js/

### ISSUE THREAD

**Issue by adm1t** [ellisonleao/sharer.js#86]
.page-header background image width is less than some displays widths. 
css 'background-size: cover' will resolve this problem. 😉

![Screenshot_2019-09-11 Sharer js by ellisonleao](https://user-images.githubusercontent.com/26100455/64705167-2e74fa80-d4b8-11e9-8de3-7c710b2616ce.png)

**Comment by ellisonleao** [comment]
hey @adm1t thanks for the suggestion! Can you open a PR to fix that, please?

**Comment by adm1t** [comment]
Yeah, of course. I did it. This is my first pr on github 😀

**Comment by ellisonleao** [comment]
Thanks! And welcome to github!
