### ISSUE TITLE
Add more social share APIs

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/sharer.js#89]
Basically the current format of a new endpoint is just by changing the `sharers` object with a new object that contains a `shareUrl`  string and the `params` object. You can see the twitter example [here](https://github.com/ellisonleao/sharer.js/blob/master/sharer.js#L89-L97)

**Comment by stanleynguyen** [comment]
Hi @ellisonleao can I take this? Do you have some platforms in mind or shall I explore what platforms are there for sharing?

**Comment by ellisonleao** [comment]
hey @stanleynguyen, thanks for reaching out. I do not have any platforms right now, so you will need to make some exploration first.

**Comment by Project-Magenta** [comment]
can i take this too?

**Comment by Project-Magenta** [comment]
willing to add hacker news and delicious

**Comment by Project-Magenta** [comment]
https://jmduke.com/2017/02/11/share-links-hacker-news

**Comment by Project-Magenta** [comment]
found this but pls dont take this will be my first pr
