### ISSUE TITLE
Update sharer.js source code variables declaration

### ISSUE THREAD

**Issue by hyuko21** [ellisonleao/sharer.js#99]
Hey, guys!

The source code from sharer.js looks awesome. It is really readable and easy to find out what's going on. Congrats!

Now, talking seriously, wouldn't it be nice if that code was using ES6 features. Like, variables declarations (const, let). 

If the code is that way because of compatibility with the browsers, I'll take it. Otherwise, I think this would be important to avoid possible unwanted bugs that this old JS var declarations might cause. What your thoughts?

Btw, if you guys find this important too, I'm up to make those changes into the code.

**Comment by ellisonleao** [comment]
hey @hyuko21 , thanks for the suggestions! i was already thinking about doing this, but i am not sure about the current status of ES6 and browser support. That's why i am stilll using the plain vanilla yet.
